import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {runInNewContext} from 'node:vm';
// Run the actual public script with a minimal DOM/canvas surface to catch missing
// IDs and runtime failures, and check that journeys require new worker events.
test('public room renders data and replays only newly observed events',async()=>{
 const html=readFileSync(new URL('../public/index.html',import.meta.url),'utf8');const elements=new Map<string,any>();const frames:Array<Function>=[];const intervals:Array<Function>=[];
 class Element{tag:string;children:any[]=[];attrs:any={};textContent='';hidden=false;style:any={setProperty(){}};classes=new Set<string>();classList={add:(k:string)=>this.classes.add(k),toggle:(k:string,on:boolean)=>on?this.classes.add(k):this.classes.delete(k),remove:(k:string)=>this.classes.delete(k)};constructor(tag:string){this.tag=tag}set id(id:string){this.attrs.id=id;elements.set(id,this)}get id(){return this.attrs.id}setAttribute(k:string,v:any){this.attrs[k]=v;if(k==='id')this.id=v}append(...items:any[]){this.children.push(...items)}replaceChildren(...items:any[]){this.children=items}getBoundingClientRect(){return{width:500,height:140}}getContext(){return{scale(){},beginPath(){},moveTo(){},lineTo(){},stroke(){},closePath(){},fill(){},arc(){},fillRect(){},fillText(){},createLinearGradient(){return{addColorStop(){}}}}}}
 for(const m of html.matchAll(/id="([^"]+)"/g)){const n=new Element('div');n.id=m[1];n.hidden=new RegExp('id="'+m[1]+'"[^>]*\\bhidden').test(html)}
 const document={getElementById:(id:string)=>elements.get(id)||null,createElement:(tag:string)=>new Element(tag),createElementNS:(_:string,tag:string)=>new Element(tag)};
 let state:any={mode:'paper',running:false,busy:false,phase:'idle',visualEvents:[],lastScan:null,feedStatus:'waiting',equity:1000,equityStale:false,cash:1000,realizedPnl:0,closedTrades:0,openPositions:[],scanned:0,eligible:0,aiEnabled:false,candidates:[],history:[],activity:[]};
 const publicFunctions=runInNewContext(html.match(/<script>([\s\S]*?)<\/script>/)![1]+';({buckets,routeFor,pointOn})',{document,window:{devicePixelRatio:1,addEventListener(){}},matchMedia:()=>({matches:false}),requestAnimationFrame:(fn:Function)=>frames.push(fn),setInterval:(fn:Function)=>intervals.push(fn),setTimeout,clearTimeout,fetch:async()=>({ok:true,json:async()=>state}),console});await new Promise(r=>setImmediate(r));
 assert.equal(elements.get('workerLabel').textContent,'WORKER STOPPED');assert.equal(elements.get('workers').children.length,8);assert.equal(elements.get('agents').children.length,9);assert.equal(elements.get('taskBubble').hidden,true);assert.equal(elements.get('social')?.textContent,undefined);
 state={...state,running:true,phase:'waiting',scanned:1,eligible:1,lastScan:new Date().toISOString(),feedStatus:'connected',candidates:[{symbol:'TEST',price:2,liquidity:100000,change:3,eligible:true}],history:[{at:1,equity:1000,symbol:'TEST',price:2},{at:2,equity:1000,symbol:'TEST',price:3}],visualEvents:[{id:1,at:Date.now(),role:'scan',message:'Reading recent Solana profiles'}]};
 // Last interval is the public refresh; resizing timers are not used here.
 await intervals.at(-1)!();assert.equal(elements.get('workerLabel').textContent,'WORKER RUNNING');assert.equal(elements.get('equityEmpty').hidden,true);assert.equal(elements.get('roomMarketEmpty').hidden,true);assert.equal(elements.get('wallSymbol').textContent,'TEST');
 frames.shift()!(100);for(let t=160;t<1500;t+=60)frames.shift()!(t);assert.equal(elements.get('taskBubble').hidden,false);assert.match(elements.get('taskBubble').textContent,/SCAN/);assert.notEqual(elements.get('agent-scan').attrs.transform,'translate(307 362)');

 const bars=publicFunctions.buckets([{at:0,price:2},{at:60000,price:4},{at:120000,price:1},{at:180000,price:3},{at:300000,price:5},{at:310000,price:NaN}]);assert.equal(bars.length,2);assert.deepEqual(JSON.parse(JSON.stringify(bars[0])),{at:0,open:2,high:4,low:1,close:3,count:4});
 assert.notDeepEqual(JSON.parse(JSON.stringify(publicFunctions.routeFor('scan').at(-1))),JSON.parse(JSON.stringify(publicFunctions.routeFor('vet').at(-1))));
 state={...state,history:[{at:0,equity:1000,symbol:'TEST',price:2},{at:60000,equity:1000,symbol:'TEST',price:3},{at:300000,equity:1000,symbol:'TEST',price:2.5}]};await intervals.at(-1)!();assert.equal(elements.get('chartMode').textContent,'5m sampled OHLC');assert.equal(elements.get('deskValue-scan').textContent,'1 PAIRS');assert.equal(elements.get('metric-vet').textContent,'1/1');
 state={...state,running:false};await intervals.at(-1)!();assert.equal(elements.get('taskBubble').hidden,true);assert.equal(elements.get('agent-scan').attrs.transform,'translate(307 362)');
});
