export const frames={ '1m':{unit:'minute',aggregate:1},'5m':{unit:'minute',aggregate:5},'1h':{unit:'hour',aggregate:1}} as const;
export const validAddress=(v:any)=>typeof v==='string'&&/^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(v);
export function parseCandles(payload:any){const list=payload?.data?.attributes?.ohlcv_list;if(!Array.isArray(list))throw Error('Invalid candle feed');const bars=new Map<number,any>();for(const row of list){if(!Array.isArray(row)||row.length<6||!row.slice(0,6).every(v=>typeof v==='number'&&Number.isFinite(v)))continue;const [time,open,high,low,close,volume]=row;if(time<0||!Number.isInteger(time)||low<=0||high<Math.max(open,close)||low>Math.min(open,close)||volume<0)continue;bars.set(time,{at:time*1000,open,high,low,close,volume});}const result=[...bars.values()].sort((a,b)=>a.at-b.at).slice(-200);if(list.length&&!result.length)throw Error('No valid candles');return result;}
// One shared cache per process. Visitors cannot choose arbitrary upstream URLs/pools.
export class MarketChart{
 cache=new Map<string,any>();inflight=new Map<string,Promise<any>>();attempts:number[]=[];
 async get(token:string,frame:keyof typeof frames,discover:(token:string)=>Promise<any>){
  const id=token+':'+frame,now=Date.now(),old=this.cache.get(id);if(old&&now-old.at<60000)return old.value;if(this.inflight.has(id))return this.inflight.get(id);
  this.attempts=this.attempts.filter(t=>now-t<60000);if(this.attempts.length>=6)return {...old?.value,status:old?.value?.candles?.length?'stale':'unavailable',message:'Chart request limit; retry shortly',source:'GeckoTerminal',candles:old?.value?.candles||[]};
  this.attempts.push(now);const task=(async()=>{let value:any;try{const pair=await discover(token);if(!validAddress(pair?.pairAddress))throw Error('Pool unavailable');const config=frames[frame],url=new URL(`https://api.geckoterminal.com/api/v2/networks/solana/pools/${pair.pairAddress}/ohlcv/${config.unit}`);url.search=new URLSearchParams({aggregate:String(config.aggregate),limit:'200',currency:'usd',token,include_empty_intervals:'false'}).toString();const response=await fetch(url,{headers:{Accept:'application/json;version=20230203'},signal:AbortSignal.timeout(12000),redirect:'error'});if(!response.ok)throw Error('Candle provider unavailable');const candles=parseCandles(await response.json());value={status:candles.length?'connected':'empty',source:'GeckoTerminal',token,pool:pair.pairAddress,symbol:String(pair.baseToken?.symbol||'TOKEN').slice(0,20),frame,currency:'USD',fetchedAt:Date.now(),lastCandleAt:candles.at(-1)?.at||null,candles,message:candles.length?'Pool OHLCV · cached 60 seconds':'No pool candles available'};}catch{value={...old?.value,status:old?.value?.candles?.length?'stale':'unavailable',source:'GeckoTerminal',token,frame,candles:old?.value?.candles||[],message:'Candle feed unavailable; retry in one minute'};}if(this.cache.size>=12&&!this.cache.has(id))this.cache.delete(this.cache.keys().next().value!);this.cache.set(id,{at:Date.now(),value});return value;})();this.inflight.set(id,task);try{return await task;}finally{this.inflight.delete(id);}
 }
}
