import {createServer} from 'node:http';
import {readFileSync,mkdirSync,chmodSync} from 'node:fs';
import {resolve} from 'node:path';
import {randomBytes,createHash} from 'node:crypto';
import {DatabaseSync} from 'node:sqlite';
import {encrypt,decrypt,verifyPassword,validOrigin} from './security.ts';
import {providerNames,testConnection,scoreJev,type Provider} from './providers.ts';
import {eligible,exitReason,fillBuy,fillSell} from './paper.ts';
const origin=process.env.APP_ORIGIN,hash=process.env.OWNER_PASSWORD_HASH;
if(!origin||!hash||!/^[a-f0-9]{64}$/.test(process.env.ENCRYPTION_KEY||''))throw new Error('Run npm run setup before starting.');
const key=Buffer.from(process.env.ENCRYPTION_KEY!,'hex');const dir=resolve(process.env.DATA_DIR||'data');mkdirSync(dir,{recursive:true,mode:0o700});chmodSync(dir,0o700);
const db=new DatabaseSync(resolve(dir,'trader.db'));db.exec(`PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS connections(name TEXT PRIMARY KEY,secret TEXT NOT NULL,tested INTEGER DEFAULT 0,message TEXT DEFAULT '',updated TEXT); CREATE TABLE IF NOT EXISTS events(id INTEGER PRIMARY KEY,at TEXT DEFAULT CURRENT_TIMESTAMP,kind TEXT,message TEXT); CREATE TABLE IF NOT EXISTS positions(id INTEGER PRIMARY KEY,token TEXT,symbol TEXT,quantity REAL,entry REAL,cost REAL,opened INTEGER,closed INTEGER,proceeds REAL,reason TEXT); CREATE TABLE IF NOT EXISTS settings(id INTEGER PRIMARY KEY CHECK(id=1),cash REAL DEFAULT 1000,ai_enabled INTEGER DEFAULT 0,ai_daily_limit INTEGER DEFAULT 20); INSERT OR IGNORE INTO settings(id) VALUES(1); CREATE TABLE IF NOT EXISTS ai_calls(id INTEGER PRIMARY KEY,day TEXT,at TEXT DEFAULT CURRENT_TIMESTAMP,status TEXT,usage TEXT);`);
chmodSync(resolve(dir,'trader.db'),0o600);
const q=(sql:string,...args:any[])=>db.prepare(sql).all(...args) as any[];
const run=(sql:string,...args:any[])=>db.prepare(sql).run(...args);
const log=(kind:string,message:string)=>run('INSERT INTO events(kind,message) VALUES(?,?)',kind,message);
db.exec('CREATE TABLE IF NOT EXISTS snapshots(id INTEGER PRIMARY KEY,at INTEGER,equity REAL,symbol TEXT,price REAL);');
let phase='idle';
let running=false,busy=false,generation=0,lastScan:string|null=null;let candidates:any[]=[];let lastError:string|null=null;
const sessions=new Map<string,{csrf:string,expires:number}>();const failures=new Map<string,{count:number,until:number}>();
const getSecret=(name:string)=>{const c=q('SELECT secret FROM connections WHERE name=?',name)[0];return c?decrypt(c.secret,key):null;};
const settings=()=>q('SELECT * FROM settings WHERE id=1')[0];
const day=()=>new Date().toISOString().slice(0,10);
const used=()=>q('SELECT count(*) n FROM ai_calls WHERE day=?',day())[0].n;
async function market(path:string){const r=await fetch('https://api.dexscreener.com/'+path,{signal:AbortSignal.timeout(12000)});if(!r.ok)throw new Error(`Market feed HTTP ${r.status}`);return r.json() as Promise<any>;}
async function tick(){if(!running||busy)return;busy=true;phase='scan';const gen=generation;try{
 const profiles=await market('token-profiles/latest/v1');if(!Array.isArray(profiles))throw new Error('Unexpected profile feed');
 const tokens=profiles.filter((x:any)=>x.chainId==='solana'&&/^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(x.tokenAddress)).slice(0,20).map((x:any)=>x.tokenAddress);
 const open=q('SELECT * FROM positions WHERE closed IS NULL');const addresses=[...new Set([...tokens,...open.map(p=>p.token)])].slice(0,30);
 const pairs=addresses.length?await market('tokens/v1/solana/'+addresses.join(',')):[];if(!Array.isArray(pairs))throw new Error('Unexpected pairs feed');
 const best=new Map<string,any>();for(const p of pairs){const token=p.baseToken?.address;if(!token)continue;const item={token,symbol:String(p.baseToken.symbol||'?').slice(0,20),price:Number(p.priceUsd),liquidity:Number(p.liquidity?.usd),volume:Number(p.volume?.h24),change:Number(p.priceChange?.m5),quoteAt:Date.now()};if(!best.has(token)||item.liquidity>best.get(token).liquidity)best.set(token,item);}
 if(!running||gen!==generation)return;
 phase='vet';candidates=[...best.values()].map(p=>({...p,eligible:eligible(p)}));
 phase='risk';for(const pos of open){const p=best.get(pos.token);if(!p||!Number.isFinite(p.price)||p.price<=0){log('risk',`Missing quote for position ${pos.id}; keeping position open`);continue;}const reason=exitReason(pos.entry,p.price,Date.now()-pos.opened);if(reason){const proceeds=fillSell(pos.quantity,p.price);db.exec('BEGIN IMMEDIATE');try{run('UPDATE positions SET closed=?,proceeds=?,reason=? WHERE id=? AND closed IS NULL',Date.now(),proceeds,reason,pos.id);run('UPDATE settings SET cash=cash+? WHERE id=1',proceeds);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}log('paper',`Closed ${pos.symbol}: ${reason}`);}}
 const s=settings();if(q('SELECT id FROM positions WHERE closed IS NULL').length<3&&s.cash>=25){let pick=candidates.filter(eligible).find(p=>!q('SELECT id FROM positions WHERE token=? AND (closed IS NULL OR opened>?)',p.token,Date.now()-3600000).length);
 if(pick&&s.ai_enabled){if(used()>=s.ai_daily_limit){log('budget','Daily AI request cap reached; new entries paused');pick=null;}else{const secret=getSecret('jev');if(!secret)throw new Error('Jev key missing');const reservation=run("INSERT INTO ai_calls(day,status) VALUES(?,'reserved')",day());try{phase='jev';const result=await scoreJev(secret,pick);run("UPDATE ai_calls SET status='completed',usage=? WHERE id=?",JSON.stringify(result.usage),reservation.lastInsertRowid);log('jev',`Candidate score ${result.score.toFixed(3)}`);if(result.score<0.8)pick=null;}catch(e){run("UPDATE ai_calls SET status='failed' WHERE id=?",reservation.lastInsertRowid);throw e;}}}
 if(pick&&running&&gen===generation&&Date.now()-pick.quoteAt<30000){phase='fills';const f=fillBuy(s.cash,25,pick.price);db.exec('BEGIN IMMEDIATE');try{run('UPDATE settings SET cash=? WHERE id=1',f.cash);run('INSERT INTO positions(token,symbol,quantity,entry,cost,opened) VALUES(?,?,?,?,?,?)',pick.token,pick.symbol,f.quantity,f.entry,25,Date.now());db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}log('paper',`Opened ${pick.symbol}, simulated $25 order`);}}
 lastScan=new Date().toISOString();lastError=null;const positions=q('SELECT * FROM positions WHERE closed IS NULL');let equity=settings().cash;for(const pos of positions){const quote=best.get(pos.token);equity+=quote&&Number.isFinite(quote.price)&&quote.price>0?fillSell(pos.quantity,quote.price):pos.cost;}const focus=candidates.find(eligible)||candidates.find(p=>Number.isFinite(p.price)&&p.price>0);run('INSERT INTO snapshots(at,equity,symbol,price) VALUES(?,?,?,?)',Date.now(),equity,focus?.symbol||null,focus?.price||null);run('DELETE FROM snapshots WHERE id NOT IN (SELECT id FROM snapshots ORDER BY id DESC LIMIT 1440)');
 }catch(e){lastError='Scan or provider request failed; no new entry from this cycle';log('error',lastError);/* Do not log upstream bodies or credentials. */}finally{busy=false;phase=running?'waiting':'idle';}}
setInterval(()=>void tick(),60000).unref();
async function body(req:any){let text='';for await(const chunk of req){text+=chunk;if(Buffer.byteLength(text)>16384)throw new Error('Request too large');}return text?JSON.parse(text):{};}
const html=readFileSync(new URL('../public/index.html',import.meta.url));
const ownerHtml=readFileSync(new URL('../public/owner.html',import.meta.url));
const server=createServer(async(req,res)=>{const path=new URL(req.url||'/',origin).pathname;const send=(code:number,value:any)=>{res.writeHead(code,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(value));};
 res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'");
 try{
 if(req.method==='GET'&&(path==='/'||path==='/owner'||path==='/owner/')){res.writeHead(200,{'Content-Type':'text/html','Cache-Control':'no-store'});res.end(path==='/'?html:ownerHtml);return;}
 if(req.method==='GET'&&path==='/api/health'){send(200,{status:'ok'});return;}
 if(req.method==='GET'&&path==='/api/public'){const s=settings();const open=q('SELECT * FROM positions WHERE closed IS NULL');const closed=q('SELECT count(*) total,COALESCE(sum(proceeds-cost),0) pnl FROM positions WHERE closed IS NOT NULL')[0];let stale=false;const marked=open.reduce((sum,p)=>{const quote=candidates.find(c=>c.token===p.token);if(!quote||!Number.isFinite(quote.price)||quote.price<=0||Date.now()-quote.quoteAt>120000){stale=true;return sum+p.cost;}return sum+fillSell(p.quantity,quote.price);},0);const count=candidates.length,accepted=candidates.filter(eligible).length;send(200,{mode:'paper',running,busy,phase,lastScan,feedStatus:lastError?'degraded':lastScan?'connected':'waiting',equity:s.cash+marked,equityStale:stale,cash:s.cash,realizedPnl:closed.pnl,closedTrades:closed.total,openPositions:open.map(p=>({symbol:p.symbol,cost:p.cost,entry:p.entry,opened:p.opened})),scanned:count,eligible:accepted,aiEnabled:!!s.ai_enabled,candidates:candidates.map(p=>({symbol:p.symbol,price:Number.isFinite(p.price)?p.price:null,liquidity:p.liquidity,change:p.change,eligible:eligible(p)})),history:q('SELECT at,equity,symbol,price FROM snapshots ORDER BY id DESC LIMIT 180').reverse(),activity:q("SELECT at,kind,message FROM events WHERE kind IN ('paper','control','risk','budget','jev') ORDER BY id DESC LIMIT 12")});return;}
 if(!path.startsWith('/api/')){send(404,{error:'Not found'});return;}
 if(req.method!=='GET'&&!validOrigin(req.headers.origin,origin!)){send(403,{error:'Invalid origin'});return;}
 if(req.method==='POST'&&path==='/api/login'){const ip=req.socket.remoteAddress||'local';const f=failures.get(ip);if(f&&f.until>Date.now()&&f.count>=5){send(429,{error:'Wait 15 minutes before another attempt'});return;}const b=await body(req);if(typeof b.password!=='string'||b.password.length>256||!verifyPassword(b.password,hash!)){const prev=f&&f.until>Date.now()?f:{count:0,until:Date.now()+900000};prev.count++;failures.set(ip,prev);send(401,{error:'Invalid password'});return;}failures.delete(ip);for(const [id,s]of sessions)if(s.expires<Date.now())sessions.delete(id);const id=randomBytes(32).toString('hex'),csrf=randomBytes(24).toString('hex');sessions.set(createHash('sha256').update(id).digest('hex'),{csrf,expires:Date.now()+8*3600000});res.setHeader('Set-Cookie',`session=${id}; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800${origin!.startsWith('https:')?'; Secure':''}`);send(200,{csrf});return;}
 const id=req.headers.cookie?.split(';').map(x=>x.trim()).find(x=>x.startsWith('session='))?.slice(8)||'';const session=sessions.get(createHash('sha256').update(id).digest('hex'));if(!session||session.expires<Date.now()){send(401,{error:'Sign in required'});return;}
 if(req.method!=='GET'&&req.headers['x-csrf-token']!==session.csrf){send(403,{error:'Invalid session token'});return;}
 if(req.method==='GET'&&path==='/api/state'){const positions=q('SELECT * FROM positions ORDER BY id DESC LIMIT 100');const s=settings();const open=positions.filter(p=>!p.closed);let stale=false;const marked=open.reduce((sum,p)=>{const quote=candidates.find(c=>c.token===p.token);if(!quote||!Number.isFinite(quote.price)||quote.price<=0||Date.now()-quote.quoteAt>120000){stale=true;return sum+p.cost;}return sum+fillSell(p.quantity,quote.price);},0);send(200,{csrf:session.csrf,running,busy,mode:'paper',lastScan,lastError,settings:s,aiCallsToday:used(),equity:s.cash+marked,equityStale:stale,candidates,positions,connections:providerNames.map(name=>({name,...q('SELECT tested,message,updated FROM connections WHERE name=?',name)[0],configured:!!q('SELECT name FROM connections WHERE name=?',name).length,activeAdapter:name==='jev',note:name==='jev'?'Optional paper scoring':name==='solana'?'Public health probe only':'Stored + connection probe only; worker adapter pending'})),events:q('SELECT * FROM events ORDER BY id DESC LIMIT 60')});return;}
 if(req.method!=='POST'){send(404,{error:'Not found'});return;}const b=await body(req);
 if(path==='/api/logout'){sessions.delete(createHash('sha256').update(id).digest('hex'));res.setHeader('Set-Cookie','session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');send(200,{ok:true});return;}
 if(path==='/api/connections'){if(running||busy){send(409,{error:'Stop and wait for the worker before changing keys'});return;}if(!providerNames.includes(b.name)||typeof b.key!=='string'||b.key.length<1||b.key.length>4096){send(400,{error:'Invalid connection'});return;}run("INSERT INTO connections(name,secret,updated) VALUES(?,?,?) ON CONFLICT(name) DO UPDATE SET secret=excluded.secret,tested=0,message='',updated=excluded.updated",b.name,encrypt(b.key,key),new Date().toISOString());log('connection',`Updated ${b.name} credential`);send(200,{ok:true});return;}
 if(path==='/api/connections/delete'){if(running||busy){send(409,{error:'Stop worker first'});return;}if(!providerNames.includes(b.name)){send(400,{error:'Unknown provider'});return;}run('DELETE FROM connections WHERE name=?',b.name);send(200,{ok:true});return;}
 if(path==='/api/connections/test'){if(!providerNames.includes(b.name)){send(400,{error:'Unknown provider'});return;}const secret=getSecret(b.name);if(!secret&&b.name!=='solana'){send(400,{error:'Save a key first'});return;}try{const result=await testConnection(b.name,secret||'');run('UPDATE connections SET tested=?,message=? WHERE name=?',result.ok?1:0,result.message,b.name);send(200,result);}catch{send(502,{error:'Connection probe failed'});}return;}
 if(path==='/api/settings'){if(running||busy){send(409,{error:'Stop worker before changing settings'});return;}if(typeof b.aiEnabled!=='boolean'||!Number.isInteger(b.aiDailyLimit)||b.aiDailyLimit<0||b.aiDailyLimit>1000){send(400,{error:'Invalid settings'});return;}run('UPDATE settings SET ai_enabled=?,ai_daily_limit=? WHERE id=1',b.aiEnabled?1:0,b.aiDailyLimit);send(200,{ok:true});return;}
 if(path==='/api/start'){if(b.mode!=='paper'){send(400,{error:'Live execution is not implemented'});return;}if(busy){send(409,{error:'Previous cycle still completing'});return;}const s=settings();if(s.ai_enabled&&!q("SELECT name FROM connections WHERE name='jev' AND tested=1").length){send(400,{error:'Save and test Jev before enabling AI scoring'});return;}if(!running){running=true;generation++;log('control','Paper worker started');void tick();}send(200,{ok:true});return;}
 if(path==='/api/stop'){running=false;generation++;log('control','Stopped entries; positions retained. Paper exits also pause.');send(200,{ok:true});return;}
 send(404,{error:'Not found'});
 }catch{send(400,{error:'Request could not be processed'});}});
server.listen(Number(process.env.PORT||9010),process.env.HOST||'127.0.0.1',()=>console.log('Agent Trader listening; worker STOPPED; paper-only'));
for(const signal of ['SIGTERM','SIGINT'])process.on(signal,()=>{running=false;generation++;server.close(()=>{db.close();process.exit(0);});setTimeout(()=>process.exit(0),20000).unref();});
