import {createServer} from 'node:http';
import {readFileSync,mkdirSync,chmodSync} from 'node:fs';
import {resolve} from 'node:path';
import {randomBytes,createHash} from 'node:crypto';
import {DatabaseSync} from 'node:sqlite';
import {encrypt,decrypt,verifyPassword,validOrigin} from './security.ts';
import {providerNames,aiProviders,defaultModels,testConnection,scoreAI,inspectToken,collectSocial,type Provider} from './providers.ts';
import {rejectionReasons,eligible,exitReason,fillBuy,fillSell} from './paper.ts';
import {MarketChart,frames,validAddress} from './market-chart.ts';
import {riskDefaults,riskInput,entryBudget} from './risk.ts';
const origin=process.env.APP_ORIGIN,hash=process.env.OWNER_PASSWORD_HASH;
if(!origin||!hash||!/^[a-f0-9]{64}$/.test(process.env.ENCRYPTION_KEY||''))throw new Error('Run npm run setup before starting.');
const key=Buffer.from(process.env.ENCRYPTION_KEY!,'hex');const dir=resolve(process.env.DATA_DIR||'data');mkdirSync(dir,{recursive:true,mode:0o700});chmodSync(dir,0o700);
const db=new DatabaseSync(resolve(dir,'trader.db'));db.exec(`PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS connections(name TEXT PRIMARY KEY,secret TEXT NOT NULL,tested INTEGER DEFAULT 0,message TEXT DEFAULT '',updated TEXT); CREATE TABLE IF NOT EXISTS events(id INTEGER PRIMARY KEY,at TEXT DEFAULT CURRENT_TIMESTAMP,kind TEXT,message TEXT); CREATE TABLE IF NOT EXISTS positions(id INTEGER PRIMARY KEY,token TEXT,symbol TEXT,quantity REAL,entry REAL,cost REAL,opened INTEGER,closed INTEGER,proceeds REAL,reason TEXT); CREATE TABLE IF NOT EXISTS settings(id INTEGER PRIMARY KEY CHECK(id=1),cash REAL DEFAULT 1000,ai_enabled INTEGER DEFAULT 0,ai_daily_limit INTEGER DEFAULT 20); INSERT OR IGNORE INTO settings(id) VALUES(1); CREATE TABLE IF NOT EXISTS ai_calls(id INTEGER PRIMARY KEY,day TEXT,at TEXT DEFAULT CURRENT_TIMESTAMP,status TEXT,usage TEXT);`);
chmodSync(resolve(dir,'trader.db'),0o600);
const q=(sql:string,...args:any[])=>db.prepare(sql).all(...args) as any[];
const run=(sql:string,...args:any[])=>db.prepare(sql).run(...args);
const log=(kind:string,message:string)=>run('INSERT INTO events(kind,message) VALUES(?,?)',kind,message);
db.exec('CREATE TABLE IF NOT EXISTS snapshots(id INTEGER PRIMARY KEY,at INTEGER,equity REAL,symbol TEXT,price REAL);');
if(!q('PRAGMA table_info(snapshots)').some(c=>c.name==='token'))db.exec('ALTER TABLE snapshots ADD COLUMN token TEXT');
db.exec('CREATE TABLE IF NOT EXISTS market_watch(id INTEGER PRIMARY KEY CHECK(id=1),token TEXT NOT NULL);');
for(const [name,definition]of Object.entries({ai_provider:"TEXT DEFAULT 'jev'",ai_model:"TEXT DEFAULT 'jev-latest'",rpc_enabled:'INTEGER DEFAULT 0',social_enabled:'INTEGER DEFAULT 0',rpc_daily_limit:'INTEGER DEFAULT 300',social_daily_limit:'INTEGER DEFAULT 20'}))if(!q('PRAGMA table_info(settings)').some(c=>c.name===name))db.exec(`ALTER TABLE settings ADD COLUMN ${name} ${definition}`);
for(const [name,value]of Object.entries(riskDefaults))if(!q('PRAGMA table_info(settings)').some(c=>c.name===name))db.exec(`ALTER TABLE settings ADD COLUMN ${name} ${typeof value==='string'?"TEXT DEFAULT '"+value+"'":'REAL DEFAULT '+value}`);
db.exec('CREATE TABLE IF NOT EXISTS risk_days(day TEXT PRIMARY KEY,baseline REAL NOT NULL);');
const chartFeed=new MarketChart();const poolCache=new Map<string,any>();let riskStatus={budget:0,reason:'Waiting for scan',dailyLoss:0};
async function discoverPool(token:string){const old=poolCache.get(token);if(old&&Date.now()-old.at<600000)return old.pair;const pairs=await market('tokens/v1/solana/'+token);const pair=Array.isArray(pairs)?pairs.filter(p=>p.chainId==='solana'&&p.baseToken?.address===token&&validAddress(p.pairAddress)).sort((a,b)=>(Number(b.liquidity?.usd)||0)-(Number(a.liquidity?.usd)||0))[0]:null;if(!pair)throw Error('No chart pool');if(poolCache.size>=40)poolCache.delete(poolCache.keys().next().value!);poolCache.set(token,{at:Date.now(),pair});return pair;}
db.exec('CREATE TABLE IF NOT EXISTS adapter_calls(id INTEGER PRIMARY KEY,day TEXT,provider TEXT,status TEXT);');
const chainCache=new Map<string,any>(),socialCache=new Map<string,any>();
function reserve(provider:string,limit:number){const n=q('SELECT count(*) n FROM adapter_calls WHERE day=? AND provider=?',day(),provider)[0].n;if(n>=limit)throw Error('Adapter daily limit');return run("INSERT INTO adapter_calls(day,provider,status) VALUES(?,?,'reserved')",day(),provider).lastInsertRowid;}
async function enrichment(provider:'solana'|'x',token:string,limit:number){const cache=provider==='solana'?chainCache:socialCache;const previous=cache.get(token);if(previous&&Date.now()-previous.at<(provider==='solana'?300000:900000))return previous.value;const id=reserve(provider,limit);try{const secret=getSecret(provider);if(!secret)throw Error('Missing credential');const value=provider==='solana'?await inspectToken(secret,token):await collectSocial(secret,token);run("UPDATE adapter_calls SET status='completed' WHERE id=?",id);if(cache.size>=200)cache.delete(cache.keys().next().value!);cache.set(token,{at:Date.now(),value});return value;}catch(e){run("UPDATE adapter_calls SET status='failed' WHERE id=?",id);throw e;}}
let phase='idle';let visualSequence=0;const visualEvents:any[]=[];
function visual(role:string,message:string){visualEvents.push({id:++visualSequence,at:Date.now(),role,message});if(visualEvents.length>80)visualEvents.shift();}

let running=false,busy=false,generation=0,lastScan:string|null=null;let candidates:any[]=[];let lastError:string|null=null;
const sessions=new Map<string,{csrf:string,expires:number}>();const failures=new Map<string,{count:number,until:number}>();
const getSecret=(name:string)=>{const c=q('SELECT secret FROM connections WHERE name=?',name)[0];return c?decrypt(c.secret,key):null;};
const settings=()=>q('SELECT * FROM settings WHERE id=1')[0];
const day=()=>new Date().toISOString().slice(0,10);
const used=()=>q('SELECT count(*) n FROM ai_calls WHERE day=?',day())[0].n;
async function market(path:string){const r=await fetch('https://api.dexscreener.com/'+path,{signal:AbortSignal.timeout(12000)});if(!r.ok)throw new Error(`Market feed HTTP ${r.status}`);return r.json() as Promise<any>;}
async function tick(){if(!running||busy)return;busy=true;phase='scan';visual('scan','Reading recent Solana profiles');const gen=generation;try{
 const profiles=await market('token-profiles/latest/v1');if(!Array.isArray(profiles))throw new Error('Unexpected profile feed');
 const tokens=profiles.filter((x:any)=>x.chainId==='solana'&&/^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(x.tokenAddress)).slice(0,20).map((x:any)=>x.tokenAddress);
 const open=q('SELECT * FROM positions WHERE closed IS NULL');const watch=q('SELECT token FROM market_watch WHERE id=1')[0]?.token;const addresses=[...new Set([...open.map(p=>p.token),...(watch?[watch]:[]),...tokens])].slice(0,30);
 visual('crawler',`Requesting market snapshots for ${addresses.length} tokens`);const pairs=addresses.length?await market('tokens/v1/solana/'+addresses.join(',')):[];if(!Array.isArray(pairs))throw new Error('Unexpected pairs feed');
 const best=new Map<string,any>();for(const p of pairs){const token=p.baseToken?.address;if(!token)continue;const value=(v:any)=>v==null||v===''?NaN:Number(v);const item={token,symbol:String(p.baseToken.symbol||'?').slice(0,20),price:value(p.priceUsd),liquidity:value(p.liquidity?.usd),volume:value(p.volume?.h24),change:value(p.priceChange?.m5),quoteAt:Date.now(),pool:p.pairAddress};if(!best.has(token)||item.liquidity>best.get(token).liquidity)best.set(token,item);}
 if(!running||gen!==generation)return;
 phase='vet';candidates=[...best.values()].map(p=>({...p,eligible:eligible(p),reasons:rejectionReasons(p)}));
 visual('vet',`Checked ${candidates.length} snapshots; ${candidates.filter(eligible).length} passed basic filters`);phase='risk';visual('risk',`Checking ${open.length} open paper positions`);for(const pos of open){const p=best.get(pos.token);if(!p||!Number.isFinite(p.price)||p.price<=0){log('risk',`Missing quote for position ${pos.id}; keeping position open`);continue;}const reason=exitReason(pos.entry,p.price,Date.now()-pos.opened);if(reason){const proceeds=fillSell(pos.quantity,p.price);db.exec('BEGIN IMMEDIATE');try{run('UPDATE positions SET closed=?,proceeds=?,reason=? WHERE id=? AND closed IS NULL',Date.now(),proceeds,reason,pos.id);run('UPDATE settings SET cash=cash+? WHERE id=1',proceeds);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}log('paper',`Closed ${pos.symbol}: ${reason}`);}}
 const s=settings(),remaining=q('SELECT * FROM positions WHERE closed IS NULL');const equityNow=s.cash+remaining.reduce((sum,pos)=>{const quote=best.get(pos.token);return sum+(quote&&Number.isFinite(quote.price)&&quote.price>0?fillSell(pos.quantity,quote.price):pos.cost);},0);run('INSERT OR IGNORE INTO risk_days(day,baseline) VALUES(?,?)',day(),s.cash+remaining.reduce((sum,p)=>sum+p.cost,0)+q('SELECT COALESCE(sum(cost-proceeds),0) loss FROM positions WHERE closed>=?',Date.parse(day()+'T00:00:00Z'))[0].loss);const dailyLoss=Math.max(0,q('SELECT baseline FROM risk_days WHERE day=?',day())[0].baseline-equityNow);const decision=entryBudget(s,remaining,dailyLoss);riskStatus={...decision,dailyLoss};const missingQuote=remaining.some(pos=>!best.has(pos.token)||!Number.isFinite(best.get(pos.token).price)||best.get(pos.token).price<=0);if(missingQuote){riskStatus.budget=0;riskStatus.reason='Open position quote unavailable; entries paused';}const budget=riskStatus.budget;visual('size',budget?`Owner limits allow $${budget.toFixed(2)} paper entry`:riskStatus.reason);if(budget>0){let pick=candidates.filter(eligible).find(p=>!q('SELECT id FROM positions WHERE token=? AND (closed IS NULL OR opened>?)',p.token,Date.now()-3600000).length);
 if(pick&&s.rpc_enabled){phase='vet';visual('vet','Checking mint authorities and token-account concentration');try{pick.chain=await enrichment('solana',pick.token,s.rpc_daily_limit);if(!pick.chain.passed){pick.reasons.push(...pick.chain.reasons);pick.eligible=false;pick=null;}}catch{pick.reasons.push('On-chain checks unavailable or daily limit reached');pick.eligible=false;pick=null;}}
 if(pick&&running&&gen===generation&&s.social_enabled){phase='social';visual('social','Collecting recent posts mentioning token address');try{pick.social=await enrichment('x',pick.token,s.social_daily_limit);log('social',`Collected ${pick.social.count} recent address mentions`);}catch{pick.reasons.push('Social evidence unavailable or daily limit reached');pick.eligible=false;pick=null;}}
 if(pick&&running&&gen===generation&&s.ai_enabled){if(used()>=s.ai_daily_limit){pick.reasons.push('Daily AI request cap reached');pick.eligible=false;log('budget','Daily AI request cap reached; new entries paused');pick=null;}else{const reservation=run("INSERT INTO ai_calls(day,status) VALUES(?,'reserved')",day());try{phase='jev';visual('jev',`Requesting ${s.ai_provider} paper watchlist evaluation`);const result=await scoreAI(s.ai_provider,getSecret(s.ai_provider)!,s.ai_model,{market:{token:pick.token,symbol:pick.symbol,price:pick.price,liquidity:pick.liquidity,volume:pick.volume,change:pick.change},chain:pick.chain||null,social:pick.social||null});run("UPDATE ai_calls SET status='completed',usage=? WHERE id=?",JSON.stringify(result.usage||{}),reservation.lastInsertRowid);pick.analysis={provider:s.ai_provider,score:result.score};log('analysis',`${s.ai_provider} watchlist score ${result.score.toFixed(3)}`);if(result.score<0.8){pick.reasons.push('AI watchlist score below 0.8');pick.eligible=false;pick=null;}}catch{run("UPDATE ai_calls SET status='failed' WHERE id=?",reservation.lastInsertRowid);pick.reasons.push('AI evaluation unavailable');pick.eligible=false;pick=null;}}}
 // Enrichment takes time: obtain a fresh quote before any paper entry.
 if(pick){if(!running||gen!==generation)return;const refreshed=await market('tokens/v1/solana/'+pick.token);const quotes=Array.isArray(refreshed)?refreshed.filter(p=>p.baseToken?.address===pick.token):[];quotes.sort((a,b)=>(Number(b.liquidity?.usd)||0)-(Number(a.liquidity?.usd)||0));const quote=quotes[0];const current={price:quote?.priceUsd==null?NaN:Number(quote.priceUsd),liquidity:quote?.liquidity?.usd==null?NaN:Number(quote.liquidity.usd),volume:quote?.volume?.h24==null?NaN:Number(quote.volume.h24),change:quote?.priceChange?.m5==null?NaN:Number(quote.priceChange.m5)};if(!eligible(current)){pick.reasons.push('Fresh quote failed market filters');pick.eligible=false;pick=null;}else{Object.assign(pick,current,{quoteAt:Date.now()});best.set(pick.token,pick);}}
 if(pick&&running&&gen===generation&&Date.now()-pick.quoteAt<30000){phase='fills';visual('fills',`Simulating entry for ${pick.symbol}`);const f=fillBuy(s.cash,budget,pick.price);db.exec('BEGIN IMMEDIATE');try{run('UPDATE settings SET cash=? WHERE id=1',f.cash);run('INSERT INTO positions(token,symbol,quantity,entry,cost,opened) VALUES(?,?,?,?,?,?)',pick.token,pick.symbol,f.quantity,f.entry,budget,Date.now());db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}log('paper',`Opened ${pick.symbol}, simulated $${budget.toFixed(2)} order`);}}
 visual('chief','Scan cycle recorded');lastScan=new Date().toISOString();lastError=null;const positions=q('SELECT * FROM positions WHERE closed IS NULL');let equity=settings().cash;for(const pos of positions){const quote=best.get(pos.token);equity+=quote&&Number.isFinite(quote.price)&&quote.price>0?fillSell(pos.quantity,quote.price):pos.cost;}const focus=watch?best.get(watch):candidates.find(eligible)||candidates.find(p=>Number.isFinite(p.price)&&p.price>0);if(!watch&&focus)run('INSERT OR REPLACE INTO market_watch(id,token) VALUES(1,?)',focus.token);run('INSERT INTO snapshots(at,equity,symbol,price,token) VALUES(?,?,?,?,?)',Date.now(),equity,focus?.symbol||null,Number.isFinite(focus?.price)&&focus.price>0?focus.price:null,focus?.token||watch||null);run('DELETE FROM snapshots WHERE id NOT IN (SELECT id FROM snapshots ORDER BY id DESC LIMIT 1440)');
 }catch(e){lastError='Scan or provider request failed; no new entry from this cycle';log('error',lastError);/* Do not log upstream bodies or credentials. */}finally{busy=false;phase=running?'waiting':'idle';}}
setInterval(()=>void tick(),60000).unref();
async function body(req:any){let text='';for await(const chunk of req){text+=chunk;if(Buffer.byteLength(text)>16384)throw new Error('Request too large');}return text?JSON.parse(text):{};}
const html=readFileSync(new URL('../public/index.html',import.meta.url));
const ownerHtml=readFileSync(new URL('../public/owner.html',import.meta.url));
const server=createServer(async(req,res)=>{const path=new URL(req.url||'/',origin).pathname;const send=(code:number,value:any)=>{res.writeHead(code,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(value));};
 res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'");
 try{
 if(req.method==='GET'&&(path==='/'||path==='/owner'||path==='/owner/')){res.writeHead(200,{'Content-Type':'text/html','Cache-Control':'no-store'});res.end(path==='/'?html:ownerHtml);return;}
 if(req.method==='GET'&&path==='/api/health'){send(200,{status:'ok'});return;}
 if(req.method==='GET'&&path==='/api/chart'){const frame=new URL(req.url||'/',origin).searchParams.get('frame')||'5m';if(!Object.hasOwn(frames,frame)){send(400,{error:'Choose 1m, 5m or 1h'});return;}const token=q('SELECT token FROM market_watch WHERE id=1')[0]?.token||'So11111111111111111111111111111111111111112';send(200,await chartFeed.get(token,frame as keyof typeof frames,discoverPool));return;}
 if(req.method==='GET'&&path==='/api/public'){const s=settings();const open=q('SELECT * FROM positions WHERE closed IS NULL');const closed=q('SELECT count(*) total,COALESCE(sum(proceeds-cost),0) pnl FROM positions WHERE closed IS NOT NULL')[0];let stale=false;const marked=open.reduce((sum,p)=>{const quote=candidates.find(c=>c.token===p.token);if(!quote||!Number.isFinite(quote.price)||quote.price<=0||Date.now()-quote.quoteAt>120000){stale=true;return sum+p.cost;}return sum+fillSell(p.quantity,quote.price);},0);const count=candidates.length,accepted=candidates.filter(p=>p.eligible).length;send(200,{mode:'paper',riskLimits:{...Object.fromEntries(Object.keys(riskDefaults).map(k=>[k,s[k]]))},riskStatus,running,busy,phase,visualEvents:visualEvents.slice(-30),lastScan,feedStatus:lastError?'degraded':lastScan?'connected':'waiting',equity:s.cash+marked,equityStale:stale,cash:s.cash,realizedPnl:closed.pnl,closedTrades:closed.total,openPositions:open.map(p=>({symbol:p.symbol,cost:p.cost,entry:p.entry,opened:p.opened})),scanned:count,eligible:accepted,aiEnabled:!!s.ai_enabled,aiProvider:s.ai_provider,socialEnabled:!!s.social_enabled,rpcEnabled:!!s.rpc_enabled,candidates:candidates.map(p=>({symbol:p.symbol,price:Number.isFinite(p.price)?p.price:null,liquidity:p.liquidity,change:p.change,volume:p.volume,eligible:p.eligible,reasons:p.reasons,chain:p.chain,analysis:p.analysis,socialCount:p.social?.count})),history:q('SELECT at,equity,symbol,price,token FROM snapshots ORDER BY id DESC LIMIT 180').reverse(),activity:q("SELECT at,kind,message FROM events WHERE kind IN ('paper','control','risk','budget','jev','analysis','social') ORDER BY id DESC LIMIT 12")});return;}
 if(!path.startsWith('/api/')){send(404,{error:'Not found'});return;}
 if(req.method!=='GET'&&!validOrigin(req.headers.origin,origin!)){send(403,{error:'Invalid origin'});return;}
 if(req.method==='POST'&&path==='/api/login'){const ip=req.socket.remoteAddress||'local';const f=failures.get(ip);if(f&&f.until>Date.now()&&f.count>=5){send(429,{error:'Wait 15 minutes before another attempt'});return;}const b=await body(req);if(typeof b.password!=='string'||b.password.length>256||!verifyPassword(b.password,hash!)){const prev=f&&f.until>Date.now()?f:{count:0,until:Date.now()+900000};prev.count++;failures.set(ip,prev);send(401,{error:'Invalid password'});return;}failures.delete(ip);for(const [id,s]of sessions)if(s.expires<Date.now())sessions.delete(id);const id=randomBytes(32).toString('hex'),csrf=randomBytes(24).toString('hex');sessions.set(createHash('sha256').update(id).digest('hex'),{csrf,expires:Date.now()+8*3600000});res.setHeader('Set-Cookie',`session=${id}; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800${origin!.startsWith('https:')?'; Secure':''}`);send(200,{csrf});return;}
 const id=req.headers.cookie?.split(';').map(x=>x.trim()).find(x=>x.startsWith('session='))?.slice(8)||'';const session=sessions.get(createHash('sha256').update(id).digest('hex'));if(!session||session.expires<Date.now()){send(401,{error:'Sign in required'});return;}
 if(req.method!=='GET'&&req.headers['x-csrf-token']!==session.csrf){send(403,{error:'Invalid session token'});return;}
 if(req.method==='GET'&&path==='/api/state'){const positions=q('SELECT * FROM positions ORDER BY id DESC LIMIT 100');const s=settings();const open=positions.filter(p=>!p.closed);let stale=false;const marked=open.reduce((sum,p)=>{const quote=candidates.find(c=>c.token===p.token);if(!quote||!Number.isFinite(quote.price)||quote.price<=0||Date.now()-quote.quoteAt>120000){stale=true;return sum+p.cost;}return sum+fillSell(p.quantity,quote.price);},0);send(200,{csrf:session.csrf,running,busy,mode:'paper',lastScan,lastError,settings:s,riskStatus,aiCallsToday:used(),adapterCallsToday:q('SELECT provider,count(*) attempts FROM adapter_calls WHERE day=? GROUP BY provider',day()),equity:s.cash+marked,equityStale:stale,candidates,positions,connections:providerNames.map(name=>({name,...q('SELECT tested,message,updated FROM connections WHERE name=?',name)[0],configured:!!q('SELECT name FROM connections WHERE name=?',name).length,activeAdapter:true,note:name==='solana'?'Helius API key · mint and token-account checks':name==='x'?'App Bearer Token · recent address mentions':name==='jev'?'Typed watchlist scoring':'JSON watchlist analysis · select provider and model in settings'})),events:q('SELECT * FROM events ORDER BY id DESC LIMIT 60')});return;}
 if(req.method!=='POST'){send(404,{error:'Not found'});return;}const b=await body(req);
 if(path==='/api/logout'){sessions.delete(createHash('sha256').update(id).digest('hex'));res.setHeader('Set-Cookie','session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');send(200,{ok:true});return;}
 if(path==='/api/connections'){if(running||busy){send(409,{error:'Stop and wait for the worker before changing keys'});return;}if(!providerNames.includes(b.name)||typeof b.key!=='string'||b.key.length<1||b.key.length>4096){send(400,{error:'Invalid connection'});return;}run("INSERT INTO connections(name,secret,updated) VALUES(?,?,?) ON CONFLICT(name) DO UPDATE SET secret=excluded.secret,tested=0,message='',updated=excluded.updated",b.name,encrypt(b.key,key),new Date().toISOString());chainCache.clear();socialCache.clear();log('connection',`Updated ${b.name} credential`);send(200,{ok:true});return;}
 if(path==='/api/connections/delete'){if(running||busy){send(409,{error:'Stop worker first'});return;}if(!providerNames.includes(b.name)){send(400,{error:'Unknown provider'});return;}run('DELETE FROM connections WHERE name=?',b.name);chainCache.clear();socialCache.clear();send(200,{ok:true});return;}
 if(path==='/api/connections/test'){if(!providerNames.includes(b.name)){send(400,{error:'Unknown provider'});return;}const saved=q('SELECT secret FROM connections WHERE name=?',b.name)[0];const secret=saved?decrypt(saved.secret,key):null;if(!secret){send(400,{error:'Save a key first'});return;}if(running||busy){send(409,{error:'Stop worker before testing connections'});return;}try{const result=await testConnection(b.name,secret||'');run('UPDATE connections SET tested=?,message=? WHERE name=? AND secret=?',result.ok?1:0,result.message,b.name,saved.secret);send(200,result);}catch{send(502,{error:'Connection probe failed'});}return;}
 if(path==='/api/settings'){if(running||busy){send(409,{error:'Stop worker before changing settings'});return;}if(typeof b.aiEnabled!=='boolean'||!Number.isInteger(b.aiDailyLimit)||b.aiDailyLimit<0||b.aiDailyLimit>1000){send(400,{error:'Invalid settings'});return;}const previous=settings(),provider=b.aiProvider??previous.ai_provider,model=b.aiModel??(provider===previous.ai_provider?previous.ai_model:defaultModels[provider as keyof typeof defaultModels]),rpcEnabled=b.rpcEnabled??!!previous.rpc_enabled,socialEnabled=b.socialEnabled??!!previous.social_enabled,rpcLimit=b.rpcDailyLimit??previous.rpc_daily_limit,socialLimit=b.socialDailyLimit??previous.social_daily_limit;if(!aiProviders.includes(provider)||typeof model!=='string'||!/^[a-zA-Z0-9_.:/-]{1,100}$/.test(model)||typeof rpcEnabled!=='boolean'||typeof socialEnabled!=='boolean'||!Number.isInteger(rpcLimit)||rpcLimit<0||rpcLimit>1000||!Number.isInteger(socialLimit)||socialLimit<0||socialLimit>1000){send(400,{error:'Invalid adapter settings'});return;}let limits;try{limits=riskInput(b,previous);}catch{send(400,{error:'Invalid paper risk limits'});return;}db.exec('BEGIN IMMEDIATE');try{run('UPDATE settings SET '+Object.keys(limits).map(k=>k+'=?').join(',')+' WHERE id=1',...Object.values(limits));run('UPDATE settings SET ai_enabled=?,ai_daily_limit=?,ai_provider=?,ai_model=?,rpc_enabled=?,social_enabled=?,rpc_daily_limit=?,social_daily_limit=? WHERE id=1',b.aiEnabled?1:0,b.aiDailyLimit,provider,model,rpcEnabled?1:0,socialEnabled?1:0,rpcLimit,socialLimit);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}log('control','Owner updated paper sizing and adapter limits');send(200,{ok:true});return;}
 if(path==='/api/start'){if(b.mode!=='paper'){send(400,{error:'Live execution is not implemented'});return;}if(busy){send(409,{error:'Previous cycle still completing'});return;}const s=settings();const required=[...(s.ai_enabled?[s.ai_provider]:[]),...(s.rpc_enabled?['solana']:[]),...(s.social_enabled?['x']:[])];for(const name of required)if(!q('SELECT name FROM connections WHERE name=? AND tested=1',name).length){send(400,{error:`Save and test ${name} before enabling its adapter`});return;}if(!running){running=true;generation++;log('control','Paper worker started');void tick();}send(200,{ok:true});return;}
 if(path==='/api/stop'){running=false;generation++;log('control','Stopped entries; positions retained. Paper exits also pause.');send(200,{ok:true});return;}
 send(404,{error:'Not found'});
 }catch{send(400,{error:'Request could not be processed'});}});
server.listen(Number(process.env.PORT||9010),process.env.HOST||'127.0.0.1',()=>console.log('Agent Trader listening; worker STOPPED; paper-only'));
for(const signal of ['SIGTERM','SIGINT'])process.on(signal,()=>{running=false;generation++;server.close(()=>{db.close();process.exit(0);});setTimeout(()=>process.exit(0),20000).unref();});
