import {createServer} from 'node:http';
import {readFileSync,mkdirSync,chmodSync} from 'node:fs';
import {resolve} from 'node:path';
import {randomBytes,createHash} from 'node:crypto';
import {DatabaseSync} from 'node:sqlite';
import {encrypt,decrypt,verifyPassword,validOrigin} from './security.ts';
import {providerNames,aiProviders,defaultModels,testConnection,scoreAI,inspectToken,collectSocial,type Provider} from './providers.ts';
import {rejectionReasons,eligible,exitReason,fillBuy,fillSell} from './paper.ts';
import {MarketChart,frames,validAddress,resolveChartPool} from './market-chart.ts';
import {WalletReader,validWallet} from './wallet.ts';
import {riskDefaults,riskInput,entryBudget} from './risk.ts';
import {Discovery,batches} from './discovery.ts';
import {fingerprint,reuseDecision,scoreThreshold} from './scoring.ts';
import {bestPools,numeric,rankPools,safeFailure} from './pools.ts';
const origin=process.env.APP_ORIGIN,hash=process.env.OWNER_PASSWORD_HASH;
if(!origin||!hash||!/^[a-f0-9]{64}$/.test(process.env.ENCRYPTION_KEY||''))throw new Error('Run npm run setup before starting.');
const key=Buffer.from(process.env.ENCRYPTION_KEY!,'hex');const dir=resolve(process.env.DATA_DIR||'data');mkdirSync(dir,{recursive:true,mode:0o700});chmodSync(dir,0o700);
const db=new DatabaseSync(resolve(dir,'trader.db'));db.exec(`PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS connections(name TEXT PRIMARY KEY,secret TEXT NOT NULL,tested INTEGER DEFAULT 0,message TEXT DEFAULT '',updated TEXT); CREATE TABLE IF NOT EXISTS events(id INTEGER PRIMARY KEY,at TEXT DEFAULT CURRENT_TIMESTAMP,kind TEXT,message TEXT); CREATE TABLE IF NOT EXISTS positions(id INTEGER PRIMARY KEY,token TEXT,symbol TEXT,quantity REAL,entry REAL,cost REAL,opened INTEGER,closed INTEGER,proceeds REAL,reason TEXT); CREATE TABLE IF NOT EXISTS settings(id INTEGER PRIMARY KEY CHECK(id=1),cash REAL DEFAULT 1000,ai_enabled INTEGER DEFAULT 0,ai_daily_limit INTEGER DEFAULT 20); INSERT OR IGNORE INTO settings(id) VALUES(1); CREATE TABLE IF NOT EXISTS ai_calls(id INTEGER PRIMARY KEY,day TEXT,at TEXT DEFAULT CURRENT_TIMESTAMP,status TEXT,usage TEXT);`);
chmodSync(resolve(dir,'trader.db'),0o600);
const q=(sql:string,...args:any[])=>db.prepare(sql).all(...args) as any[];
const run=(sql:string,...args:any[])=>db.prepare(sql).run(...args);
const log=(kind:string,message:string)=>run('INSERT INTO events(kind,message) VALUES(?,?)',kind,message);
db.exec('CREATE TABLE IF NOT EXISTS snapshots(id INTEGER PRIMARY KEY,at INTEGER,equity REAL,symbol TEXT,price REAL);');
if(!q('PRAGMA table_info(snapshots)').some(c=>c.name==='token'))db.exec('ALTER TABLE snapshots ADD COLUMN token TEXT');
db.exec('CREATE TABLE IF NOT EXISTS market_watch(id INTEGER PRIMARY KEY CHECK(id=1),token TEXT NOT NULL);');
for(const [name,definition]of Object.entries({ai_provider:"TEXT DEFAULT 'jev'",ai_model:"TEXT DEFAULT 'jev-latest'",rpc_enabled:'INTEGER DEFAULT 0',social_enabled:'INTEGER DEFAULT 0',rpc_daily_limit:'INTEGER DEFAULT 300',social_daily_limit:'INTEGER DEFAULT 20'}))if(!q('PRAGMA table_info(settings)').some(c=>c.name===name))db.exec(`ALTER TABLE settings ADD COLUMN ${name} ${definition}`);
for(const [name,value]of Object.entries(riskDefaults))if(!q('PRAGMA table_info(settings)').some(c=>c.name===name))db.exec(`ALTER TABLE settings ADD COLUMN ${name} ${typeof value==='string'?"TEXT DEFAULT '"+value+"'":'REAL DEFAULT '+value}`);
if(!q('PRAGMA table_info(settings)').some(c=>c.name==='ai_min_score'))db.exec('ALTER TABLE settings ADD COLUMN ai_min_score REAL DEFAULT 0.8');
if(!q('PRAGMA table_info(settings)').some(c=>c.name==='ai_interval_minutes'))db.exec('ALTER TABLE settings ADD COLUMN ai_interval_minutes REAL DEFAULT 60');
db.exec('CREATE TABLE IF NOT EXISTS candidate_visits(token TEXT PRIMARY KEY,at INTEGER);');
db.exec('CREATE TABLE IF NOT EXISTS ai_evaluations(provider TEXT,model TEXT,token TEXT,at INTEGER,fingerprint TEXT,score REAL,error_code TEXT,PRIMARY KEY(provider,model,token));');
for(const [name,def]of Object.entries({ai_score:'REAL',ai_provider:'TEXT',ai_model:'TEXT'}))if(!q('PRAGMA table_info(positions)').some(c=>c.name===name))db.exec(`ALTER TABLE positions ADD COLUMN ${name} ${def}`);
db.exec('CREATE TABLE IF NOT EXISTS risk_days(day TEXT PRIMARY KEY,baseline REAL NOT NULL);');
db.exec('CREATE TABLE IF NOT EXISTS owner_wallet(id INTEGER PRIMARY KEY CHECK(id=1),address TEXT NOT NULL,updated TEXT NOT NULL);');const walletReader=new WalletReader();
const discovery=new Discovery();let discoveryStatus:any={sources:[],remembered:0};const chartFeed=new MarketChart();const poolCache=new Map<string,any>();let riskStatus={budget:0,reason:'Waiting for scan',dailyLoss:0};
async function discoverPool(token:string){const old=poolCache.get(token);if(old&&Date.now()-old.at<600000)return old.pair;const pair=await resolveChartPool(token,t=>market('tokens/v1/solana/'+t));if(poolCache.size>=40)poolCache.delete(poolCache.keys().next().value!);poolCache.set(token,{at:Date.now(),pair});return pair;}
db.exec('CREATE TABLE IF NOT EXISTS adapter_calls(id INTEGER PRIMARY KEY,day TEXT,provider TEXT,status TEXT);');
db.exec('CREATE TABLE IF NOT EXISTS scan_audit(id INTEGER PRIMARY KEY,at INTEGER,cycle INTEGER,token TEXT,symbol TEXT,stage TEXT,outcome TEXT,reasons TEXT);');
for(const [name,def]of Object.entries({provider:"TEXT DEFAULT 'unknown'",model:"TEXT DEFAULT ''",purpose:"TEXT DEFAULT 'legacy'",error_code:"TEXT DEFAULT ''"}))if(!q('PRAGMA table_info(ai_calls)').some(c=>c.name===name))db.exec(`ALTER TABLE ai_calls ADD COLUMN ${name} ${def}`);
function audit(cycle:number,p:any,stage:string,outcome:string,reasons:string[]=[]){run('INSERT INTO scan_audit(at,cycle,token,symbol,stage,outcome,reasons) VALUES(?,?,?,?,?,?,?)',Date.now(),cycle,p?.token||null,p?.symbol||null,stage,outcome,JSON.stringify(reasons));}
const chainCache=new Map<string,any>(),socialCache=new Map<string,any>();
function reserve(provider:string,limit:number){const n=q('SELECT count(*) n FROM adapter_calls WHERE day=? AND provider=?',day(),provider)[0].n;if(n>=limit)throw Error('Adapter daily limit');return run("INSERT INTO adapter_calls(day,provider,status) VALUES(?,?,'reserved')",day(),provider).lastInsertRowid;}
async function enrichment(provider:'solana'|'x',token:string,limit:number){const cache=provider==='solana'?chainCache:socialCache;const previous=cache.get(token);if(previous&&Date.now()-previous.at<(provider==='solana'?300000:900000))return previous.value;const id=reserve(provider,limit);try{const secret=getSecret(provider);if(!secret)throw Error('Missing credential');const value=provider==='solana'?await inspectToken(secret,token):await collectSocial(secret,token);run("UPDATE adapter_calls SET status='completed' WHERE id=?",id);if(cache.size>=200)cache.delete(cache.keys().next().value!);cache.set(token,{at:Date.now(),value});return value;}catch(e){run("UPDATE adapter_calls SET status='failed' WHERE id=?",id);throw e;}}
let phase='idle';let visualSequence=0;const visualEvents:any[]=[];
function visual(role:string,message:string){visualEvents.push({id:++visualSequence,at:Date.now(),role,message});if(visualEvents.length>80)visualEvents.shift();}

const bootedAt=new Date().toISOString();log('control','Service started; paper worker stopped. Owner must click Start.');
let running=false,busy=false,generation=0,lastScan:string|null=null;let candidates:any[]=[];let lastError:string|null=null;
const sessions=new Map<string,{csrf:string,expires:number}>();const failures=new Map<string,{count:number,until:number}>();
const getSecret=(name:string)=>{const c=q('SELECT secret FROM connections WHERE name=?',name)[0];return c?decrypt(c.secret,key):null;};
const settings=()=>q('SELECT * FROM settings WHERE id=1')[0];
const day=()=>new Date().toISOString().slice(0,10);
const used=()=>q('SELECT count(*) n FROM ai_calls WHERE day=?',day())[0].n;
async function market(path:string){const r=await fetch('https://api.dexscreener.com/'+path,{signal:AbortSignal.timeout(12000)});if(!r.ok)throw new Error(`Market feed HTTP ${r.status}`);return r.json() as Promise<any>;}
function budgetReason(p:any){if(!riskStatus.budget)return riskStatus.reason;if(q('SELECT id FROM positions WHERE token=? AND (closed IS NULL OR opened>?)',p.token,Date.now()-3600000).length)return 'Position already open or one-hour token cooldown';return 'Not selected: worker evaluates at most one candidate per cycle';}
function paidAIBlocked(s:any){if(used()>=s.ai_daily_limit)return 'Daily AI request cap reached';return q("SELECT id FROM ai_calls WHERE purpose='worker' AND at>? LIMIT 1",new Date(Date.now()-s.ai_interval_minutes*60000).toISOString().slice(0,19).replace('T',' ')).length?`Paid AI pacing: at least ${s.ai_interval_minutes} minutes between new worker requests`:null;}
async function tick(){if(!running||busy)return;busy=true;phase='scan';visual('scan','Reading recent Solana profiles');const gen=generation,cycle=Date.now();let auditCandidates:any[]=[];try{
 const discovered=await discovery.read(market);discoveryStatus={sources:discovered.sources,remembered:discovered.remembered};
 const open=q('SELECT * FROM positions WHERE closed IS NULL');const watch=q('SELECT token FROM market_watch WHERE id=1')[0]?.token;
 const addresses=[...new Set([...open.map(p=>p.token),...(watch?[watch]:[]),...discovered.tokens])];
 visual('crawler',`Requesting market snapshots for ${addresses.length} tokens`);
 const results=await Promise.allSettled(batches(addresses).map(batch=>market('tokens/v1/solana/'+batch.join(','))));
 const pairs:any[]=[];for(const r of results){if(r.status==='fulfilled'&&Array.isArray(r.value))pairs.push(...r.value);else audit(cycle,null,'discovery','failed',[r.status==='rejected'?safeFailure(r.reason):'invalid_response']);}
 if(!pairs.length&&addresses.length)throw Error('Invalid response from all quote batches');
 const best=new Map<string,any>();for(const [token,p]of bestPools(pairs,addresses)){best.set(token,{token,symbol:String(p.baseToken.symbol||'?').slice(0,20),price:numeric(p.priceUsd),liquidity:numeric(p.liquidity?.usd),volume:numeric(p.volume?.h24),change:numeric(p.priceChange?.m5),quoteAt:Date.now(),pool:p.pairAddress});}
 if(!running||gen!==generation)return;
 phase='vet';candidates=[...best.values()].map(p=>({...p,eligible:eligible(p),stage:eligible(p)?'selection':'market',outcome:eligible(p)?'skipped':'rejected',reasons:rejectionReasons(p)}));for(const token of addresses)if(!best.has(token))candidates.push({token,symbol:token.slice(0,8),eligible:false,stage:'market',outcome:'rejected',reasons:['Market quote unavailable']});auditCandidates=candidates;
 visual('vet',`Checked ${candidates.length} snapshots; ${candidates.filter(eligible).length} passed basic filters`);phase='risk';visual('risk',`Checking ${open.length} open paper positions`);for(const pos of open){const p=best.get(pos.token);if(!p||!Number.isFinite(p.price)||p.price<=0){log('risk',`Missing quote for position ${pos.id}; keeping position open`);continue;}const reason=exitReason(pos.entry,p.price,Date.now()-pos.opened);if(reason){const proceeds=fillSell(pos.quantity,p.price);db.exec('BEGIN IMMEDIATE');try{run('UPDATE positions SET closed=?,proceeds=?,reason=? WHERE id=? AND closed IS NULL',Date.now(),proceeds,reason,pos.id);run('UPDATE settings SET cash=cash+? WHERE id=1',proceeds);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}log('paper',`Closed ${pos.symbol}: ${reason}`);}}
 const s=settings(),remaining=q('SELECT * FROM positions WHERE closed IS NULL');const equityNow=s.cash+remaining.reduce((sum,pos)=>{const quote=best.get(pos.token);return sum+(quote&&Number.isFinite(quote.price)&&quote.price>0?fillSell(pos.quantity,quote.price):pos.cost);},0);run('INSERT OR IGNORE INTO risk_days(day,baseline) VALUES(?,?)',day(),s.cash+remaining.reduce((sum,p)=>sum+p.cost,0)+q('SELECT COALESCE(sum(cost-proceeds),0) loss FROM positions WHERE closed>=?',Date.parse(day()+'T00:00:00Z'))[0].loss);const dailyLoss=Math.max(0,q('SELECT baseline FROM risk_days WHERE day=?',day())[0].baseline-equityNow);const decision=entryBudget(s,remaining,dailyLoss);riskStatus={...decision,dailyLoss};const missingQuote=remaining.some(pos=>!best.has(pos.token)||!Number.isFinite(best.get(pos.token).price)||best.get(pos.token).price<=0);if(missingQuote){riskStatus.budget=0;riskStatus.reason='Open position quote unavailable; entries paused';}const budget=riskStatus.budget;audit(cycle,null,'risk',budget>0?'passed':'blocked',[riskStatus.reason]);visual('size',budget?`Owner limits allow $${budget.toFixed(2)} paper entry`:riskStatus.reason);if(budget>0){let pick=candidates.filter(eligible).sort((a,b)=>{const last=(p:any)=>q('SELECT at FROM candidate_visits WHERE token=?',p.token)[0]?.at||0;return last(a)-last(b)||b.liquidity-a.liquidity;}).find(p=>!q('SELECT id FROM positions WHERE token=? AND (closed IS NULL OR opened>?)',p.token,Date.now()-3600000).length);
 if(pick){run('INSERT INTO candidate_visits(token,at) VALUES(?,?) ON CONFLICT(token) DO UPDATE SET at=excluded.at',pick.token,Date.now());pick.stage='entry';pick.outcome='passed';}
 if(pick&&s.ai_enabled){const previous=q('SELECT * FROM ai_evaluations WHERE provider=? AND model=? AND token=?',s.ai_provider,s.ai_model,pick.token)[0];const cachedPossible=previous&&Number.isFinite(previous.score)&&Date.now()-previous.at<1800000;const blocked=paidAIBlocked(s);if(blocked&&!cachedPossible){pick.stage='ai';pick.reasons.push(blocked);pick.eligible=false;pick=null;}}
 if(pick&&s.rpc_enabled){phase='vet';visual('vet','Checking mint authorities and token-account concentration');try{pick.stage='chain';pick.chain=await enrichment('solana',pick.token,s.rpc_daily_limit);if(!pick.chain.passed){pick.reasons.push(...pick.chain.reasons);pick.eligible=false;pick=null;}}catch(e){pick.stage='chain';pick.reasons.push('On-chain check failed: '+safeFailure(e));pick.eligible=false;pick=null;}}
 if(pick&&running&&gen===generation&&s.social_enabled){phase='social';visual('social','Collecting recent posts mentioning token address');try{pick.stage='social';pick.social=await enrichment('x',pick.token,s.social_daily_limit);log('social',`Collected ${pick.social.count} recent address mentions`);}catch(e){pick.reasons.push('Social check failed: '+safeFailure(e));pick.eligible=false;pick=null;}}
 if(pick&&running&&gen===generation&&s.ai_enabled){
  pick.stage='ai';const selected=pick;
  const state={market:{token:pick.token,symbol:pick.symbol,price:pick.price,liquidity:pick.liquidity,volume:pick.volume,change:pick.change},chain:pick.chain||null,social:pick.social||null};
  const stateHash=fingerprint(state),previous=q('SELECT * FROM ai_evaluations WHERE provider=? AND model=? AND token=?',s.ai_provider,s.ai_model,pick.token)[0],reuse=reuseDecision(previous,stateHash);
  let score:number|undefined;
  if(reuse==='cached'){score=previous.score;selected.analysis={provider:s.ai_provider,score,cached:true};selected.reasons.push('Reused recent AI evaluation; no paid request');}
  else if(reuse==='cooldown'){selected.reasons.push('AI token cooldown: wait 15 minutes before another paid evaluation');selected.eligible=false;pick=null;}
  else if(used()>=s.ai_daily_limit){selected.reasons.push('Daily AI request cap reached');selected.eligible=false;pick=null;}
  else if(q("SELECT id FROM ai_calls WHERE purpose='worker' AND at>? LIMIT 1",new Date(Date.now()-s.ai_interval_minutes*60000).toISOString().slice(0,19).replace('T',' ')).length){selected.reasons.push(`Paid AI pacing: at least ${s.ai_interval_minutes} minutes between new worker requests`);selected.eligible=false;pick=null;}
  else {const reservation=run("INSERT INTO ai_calls(day,status,provider,model,purpose) VALUES(?,'reserved',?,?,'worker')",day(),s.ai_provider,s.ai_model);
   const save=(score:number|null,error:string)=>run('INSERT INTO ai_evaluations(provider,model,token,at,fingerprint,score,error_code) VALUES(?,?,?,?,?,?,?) ON CONFLICT(provider,model,token) DO UPDATE SET at=excluded.at,fingerprint=excluded.fingerprint,score=excluded.score,error_code=excluded.error_code',s.ai_provider,s.ai_model,selected.token,Date.now(),stateHash,score,error);
   save(null,'reserved');try{phase='jev';visual('jev',`Requesting ${s.ai_provider} paper watchlist evaluation`);const result=await scoreAI(s.ai_provider,getSecret(s.ai_provider)!,s.ai_model,state);score=result.score;save(score,'');run("UPDATE ai_calls SET status='completed',usage=? WHERE id=?",JSON.stringify(result.usage||{}),reservation.lastInsertRowid);selected.analysis={provider:s.ai_provider,score};log('analysis',`${s.ai_provider} watchlist score ${score.toFixed(3)}`);}
   catch(e){const failure=safeFailure(e);save(null,failure);run("UPDATE ai_calls SET status='failed',error_code=? WHERE id=?",failure,reservation.lastInsertRowid);selected.reasons.push('AI evaluation failed: '+failure);selected.eligible=false;pick=null;}
  }
  if(pick&&score!==undefined&&score<s.ai_min_score){selected.reasons.push(`AI watchlist score ${score.toFixed(3)} below owner threshold ${s.ai_min_score}`);selected.eligible=false;pick=null;}
 }
 // Enrichment takes time: obtain a fresh quote before any paper entry.
 if(pick){if(!running||gen!==generation)return;pick.stage='quote';const refreshed=await market('tokens/v1/solana/'+pick.token);const quotes=Array.isArray(refreshed)?refreshed.filter(p=>p.baseToken?.address===pick.token):[];quotes.sort(rankPools);const quote=quotes[0];const current={price:quote?.priceUsd==null?NaN:Number(quote.priceUsd),liquidity:quote?.liquidity?.usd==null?NaN:Number(quote.liquidity.usd),volume:quote?.volume?.h24==null?NaN:Number(quote.volume.h24),change:quote?.priceChange?.m5==null?NaN:Number(quote.priceChange.m5)};if(!eligible(current)){pick.reasons.push('Fresh quote failed market filters');pick.eligible=false;pick=null;}else{Object.assign(pick,current,{quoteAt:Date.now()});best.set(pick.token,pick);}}
 if(pick&&running&&gen===generation&&Date.now()-pick.quoteAt<30000){pick.stage='fill';phase='fills';visual('fills',`Simulating entry for ${pick.symbol}`);const f=fillBuy(s.cash,budget,pick.price);db.exec('BEGIN IMMEDIATE');try{run('UPDATE settings SET cash=? WHERE id=1',f.cash);run('INSERT INTO positions(token,symbol,quantity,entry,cost,opened,ai_score,ai_provider,ai_model) VALUES(?,?,?,?,?,?,?,?,?)',pick.token,pick.symbol,f.quantity,f.entry,budget,Date.now(),pick.analysis?.score??null,pick.analysis?s.ai_provider:null,pick.analysis?s.ai_model:null);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}pick.outcome='filled';log('paper',`Opened ${pick.symbol}, simulated $${budget.toFixed(2)} order`);}}
 visual('chief','Scan cycle recorded');lastScan=new Date().toISOString();lastError=null;const positions=q('SELECT * FROM positions WHERE closed IS NULL');let equity=settings().cash;for(const pos of positions){const quote=best.get(pos.token);equity+=quote&&Number.isFinite(quote.price)&&quote.price>0?fillSell(pos.quantity,quote.price):pos.cost;}const focus=watch?best.get(watch):candidates.find(eligible)||candidates.find(p=>Number.isFinite(p.price)&&p.price>0);if(!watch&&focus)run('INSERT OR REPLACE INTO market_watch(id,token) VALUES(1,?)',focus.token);run('INSERT INTO snapshots(at,equity,symbol,price,token) VALUES(?,?,?,?,?)',Date.now(),equity,focus?.symbol||null,Number.isFinite(focus?.price)&&focus.price>0?focus.price:null,focus?.token||watch||null);run('DELETE FROM snapshots WHERE id NOT IN (SELECT id FROM snapshots ORDER BY id DESC LIMIT 1440)');
 }catch(e){for(const p of auditCandidates)if(!['market','selection'].includes(p.stage)&&p.outcome!=='filled'){p.eligible=false;p.reasons.push('Cycle interrupted: '+safeFailure(e));}audit(cycle,null,'cycle','failed',[safeFailure(e)]);lastError='Scan or provider request failed ('+safeFailure(e)+'); no new entry from this cycle';log('error',lastError);/* Do not log upstream bodies or credentials. */}finally{for(const p of auditCandidates){if(gen!==generation&&p.eligible&&p.outcome!=='filled'){p.outcome='skipped';p.reasons.push('Worker stopped before entry');}const reasons=p.stage==='selection'?[budgetReason(p)]:p.reasons;audit(cycle,p,p.stage||'market',p.eligible?(p.outcome||'passed'):'rejected',reasons);}run('DELETE FROM scan_audit WHERE id NOT IN (SELECT id FROM scan_audit ORDER BY id DESC LIMIT 30000)');busy=false;phase=running?'waiting':'idle';}}
setInterval(()=>void tick(),60000).unref();
async function body(req:any){let text='';for await(const chunk of req){text+=chunk;if(Buffer.byteLength(text)>16384)throw new Error('Request too large');}return text?JSON.parse(text):{};}
const html=readFileSync(new URL('../public/index.html',import.meta.url));
const ownerHtml=readFileSync(new URL('../public/owner.html',import.meta.url));
const server=createServer(async(req,res)=>{const path=new URL(req.url||'/',origin).pathname;const send=(code:number,value:any)=>{res.writeHead(code,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(value));};
 res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'");
 try{
 if(req.method==='GET'&&(path==='/'||path==='/owner'||path==='/owner/'||/^\/owner\/(overview|connections|settings|wallet|trades)$/.test(path))){res.writeHead(200,{'Content-Type':'text/html','Cache-Control':'no-store'});res.end(path==='/'?html:ownerHtml);return;}
 if(req.method==='GET'&&path==='/api/health'){send(200,{status:'ok'});return;}
 if(req.method==='GET'&&path==='/api/chart'){const frame=new URL(req.url||'/',origin).searchParams.get('frame')||'5m';if(!Object.hasOwn(frames,frame)){send(400,{error:'Choose 1m, 5m or 1h'});return;}const token=q('SELECT token FROM market_watch WHERE id=1')[0]?.token||'So11111111111111111111111111111111111111112';send(200,await chartFeed.recovered(token,frame as keyof typeof frames,discoverPool));return;}
 if(req.method==='GET'&&path==='/api/public'){const s=settings();const open=q('SELECT * FROM positions WHERE closed IS NULL');const closed=q('SELECT count(*) total,COALESCE(sum(proceeds-cost),0) pnl FROM positions WHERE closed IS NOT NULL')[0];let stale=false;const marked=open.reduce((sum,p)=>{const quote=candidates.find(c=>c.token===p.token);if(!quote||!Number.isFinite(quote.price)||quote.price<=0||Date.now()-quote.quoteAt>120000){stale=true;return sum+p.cost;}return sum+fillSell(p.quantity,quote.price);},0);const count=candidates.length,accepted=candidates.filter(p=>p.eligible).length;send(200,{mode:'paper',riskLimits:{...Object.fromEntries(Object.keys(riskDefaults).map(k=>[k,s[k]]))},riskStatus,running,busy,phase,visualEvents:visualEvents.slice(-30),lastScan,feedStatus:lastError?'degraded':lastScan?'connected':'waiting',equity:s.cash+marked,equityStale:stale,cash:s.cash,realizedPnl:closed.pnl,closedTrades:closed.total,openPositions:open.map(p=>({symbol:p.symbol,cost:p.cost,entry:p.entry,opened:p.opened})),scanned:count,eligible:accepted,aiEnabled:!!s.ai_enabled,aiProvider:s.ai_provider,socialEnabled:!!s.social_enabled,rpcEnabled:!!s.rpc_enabled,candidates:candidates.map(p=>({symbol:p.symbol,price:Number.isFinite(p.price)?p.price:null,liquidity:p.liquidity,change:p.change,volume:p.volume,eligible:p.eligible,reasons:p.reasons,chain:p.chain,analysis:p.analysis,socialCount:p.social?.count})),history:q('SELECT at,equity,symbol,price,token FROM snapshots ORDER BY id DESC LIMIT 180').reverse(),activity:q("SELECT at,kind,message FROM events WHERE kind IN ('paper','control','risk','budget','jev','analysis','social') ORDER BY id DESC LIMIT 12")});return;}
 if(!path.startsWith('/api/')){send(404,{error:'Not found'});return;}
 if(req.method!=='GET'&&!validOrigin(req.headers.origin,origin!)){send(403,{error:'Invalid origin'});return;}
 if(req.method==='POST'&&path==='/api/login'){const ip=req.socket.remoteAddress||'local';const f=failures.get(ip);if(f&&f.until>Date.now()&&f.count>=5){send(429,{error:'Wait 15 minutes before another attempt'});return;}const b=await body(req);if(typeof b.password!=='string'||b.password.length>256||!verifyPassword(b.password,hash!)){const prev=f&&f.until>Date.now()?f:{count:0,until:Date.now()+900000};prev.count++;failures.set(ip,prev);send(401,{error:'Invalid password'});return;}failures.delete(ip);for(const [id,s]of sessions)if(s.expires<Date.now())sessions.delete(id);const id=randomBytes(32).toString('hex'),csrf=randomBytes(24).toString('hex');sessions.set(createHash('sha256').update(id).digest('hex'),{csrf,expires:Date.now()+8*3600000});res.setHeader('Set-Cookie',`session=${id}; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800${origin!.startsWith('https:')?'; Secure':''}`);send(200,{csrf});return;}
 const id=req.headers.cookie?.split(';').map(x=>x.trim()).find(x=>x.startsWith('session='))?.slice(8)||'';const session=sessions.get(createHash('sha256').update(id).digest('hex'));if(!session||session.expires<Date.now()){send(401,{error:'Sign in required'});return;}
 if(req.method!=='GET'&&req.headers['x-csrf-token']!==session.csrf){send(403,{error:'Invalid session token'});return;}
 if(req.method==='GET'&&path==='/api/wallet'){const saved=q('SELECT address,updated FROM owner_wallet WHERE id=1')[0];if(!saved){send(200,{configured:false,readOnly:true,status:'unconfigured'});return;}const secret=getSecret('solana');if(!secret){send(200,{configured:true,...saved,readOnly:true,status:'unavailable',message:'Save a Helius key on Connections to read this wallet'});return;}const snapshot=await walletReader.read(saved.address,secret);const current=q('SELECT address FROM owner_wallet WHERE id=1')[0];if(current?.address!==saved.address){send(409,{error:'Wallet address changed; refresh again'});return;}send(200,{configured:true,updated:saved.updated,...snapshot});return;}
 if(req.method==='GET'&&path==='/api/state'){const positions=q('SELECT * FROM positions ORDER BY id DESC LIMIT 100');const s=settings();const open=positions.filter(p=>!p.closed);let stale=false;const marked=open.reduce((sum,p)=>{const quote=candidates.find(c=>c.token===p.token);if(!quote||!Number.isFinite(quote.price)||quote.price<=0||Date.now()-quote.quoteAt>120000){stale=true;return sum+p.cost;}return sum+fillSell(p.quantity,quote.price);},0);send(200,{csrf:session.csrf,running,busy,mode:'paper',bootedAt,workerWarning:!running?'WORKER STOPPED: no scans, entries or exits. Click Start after a service restart.':lastScan&&Date.now()-Date.parse(lastScan)>180000?'No completed scan in over three minutes; inspect errors.':null,discoveryStatus,paperScoreOutcomes:q('SELECT count(*) closed,sum(CASE WHEN proceeds>cost THEN 1 ELSE 0 END) wins,COALESCE(sum(proceeds-cost),0) pnl FROM positions WHERE closed IS NOT NULL AND ai_score IS NOT NULL AND ai_provider=? AND ai_model=?',s.ai_provider,s.ai_model)[0],scoreSummary:q('SELECT count(*) total,min(score) minimum,max(score) maximum,avg(score) average,sum(CASE WHEN score>=? THEN 1 ELSE 0 END) passing FROM ai_evaluations WHERE provider=? AND model=? AND score IS NOT NULL AND at>=?',settings().ai_min_score,settings().ai_provider,settings().ai_model,Date.now()-604800000)[0],lastScan,lastError,settings:s,riskStatus,diagnostics:q('SELECT * FROM scan_audit ORDER BY id DESC LIMIT 100').map(r=>({...r,reasons:JSON.parse(r.reasons)})),diagnosticSummary:q('SELECT stage,outcome,count(*) total FROM scan_audit WHERE at>=? GROUP BY stage,outcome',Date.now()-3600000),aiRequests:q('SELECT at,status,provider,model,purpose,error_code FROM ai_calls ORDER BY id DESC LIMIT 20'),aiCallsToday:used(),adapterCallsToday:q('SELECT provider,count(*) attempts FROM adapter_calls WHERE day=? GROUP BY provider',day()),equity:s.cash+marked,equityStale:stale,candidates,positions,connections:providerNames.map(name=>({name,...q('SELECT tested,message,updated FROM connections WHERE name=?',name)[0],configured:!!q('SELECT name FROM connections WHERE name=?',name).length,activeAdapter:true,note:name==='solana'?'Helius API key · mint and token-account checks':name==='x'?'App Bearer Token · recent address mentions':name==='jev'?'Typed watchlist scoring':'JSON watchlist analysis · select provider and model in settings'})),events:q('SELECT * FROM events ORDER BY id DESC LIMIT 60')});return;}
 if(req.method!=='POST'){send(404,{error:'Not found'});return;}const b=await body(req);
 if(path==='/api/wallet'){if(running||busy){send(409,{error:'Stop and wait for the worker before changing the watched address'});return;}if(b.address===null){run('DELETE FROM owner_wallet WHERE id=1');walletReader.clear();log('control','Removed watched wallet address');send(200,{ok:true});return;}if(!validWallet(b.address)||b.confirmAddress!==true){send(400,{error:'Enter a valid Solana public address and confirm it. Never enter a seed phrase or private key.'});return;}run('INSERT INTO owner_wallet(id,address,updated) VALUES(1,?,?) ON CONFLICT(id) DO UPDATE SET address=excluded.address,updated=excluded.updated',b.address,new Date().toISOString());walletReader.clear();log('control','Updated read-only watched wallet address');send(200,{ok:true});return;}
 if(path==='/api/logout'){sessions.delete(createHash('sha256').update(id).digest('hex'));res.setHeader('Set-Cookie','session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');send(200,{ok:true});return;}
 if(path==='/api/connections'){if(running||busy){send(409,{error:'Stop and wait for the worker before changing keys'});return;}if(!providerNames.includes(b.name)||typeof b.key!=='string'||b.key.length<1||b.key.length>4096){send(400,{error:'Invalid connection'});return;}run("INSERT INTO connections(name,secret,updated) VALUES(?,?,?) ON CONFLICT(name) DO UPDATE SET secret=excluded.secret,tested=0,message='',updated=excluded.updated",b.name,encrypt(b.key,key),new Date().toISOString());chainCache.clear();socialCache.clear();walletReader.clear();log('connection',`Updated ${b.name} credential`);send(200,{ok:true});return;}
 if(path==='/api/connections/delete'){if(running||busy){send(409,{error:'Stop worker first'});return;}if(!providerNames.includes(b.name)){send(400,{error:'Unknown provider'});return;}run('DELETE FROM connections WHERE name=?',b.name);chainCache.clear();socialCache.clear();walletReader.clear();send(200,{ok:true});return;}
 if(path==='/api/connections/inference-test'){if(running||busy){send(409,{error:'Stop and wait for worker before inference testing'});return;}if(b.name!=='jev'||b.confirmUsage!==true){send(400,{error:'Confirm one paid Jev diagnostic request'});return;}const s=settings(),secret=getSecret('jev');if(!secret){send(400,{error:'Save a Jev key first'});return;}if(used()>=s.ai_daily_limit||q("SELECT id FROM ai_calls WHERE day=? AND purpose='probe'",day()).length){send(429,{error:'AI daily limit reached or diagnostic already attempted today (UTC)'});return;}const model=s.ai_provider==='jev'?s.ai_model:defaultModels.jev;const reservation=run("INSERT INTO ai_calls(day,status,provider,model,purpose) VALUES(?,'reserved','jev',?,'probe')",day(),model);busy=true;try{const result=await scoreAI('jev',secret,model,{diagnostic:true,market:{token:'DIAGNOSTIC_ONLY',symbol:'TEST',price:100,liquidity:1000000,volume:2000000,change:2},chain:null,social:null,note:'Synthetic diagnostic fixture. No trade is permitted.'});run("UPDATE ai_calls SET status='completed',usage=? WHERE id=?",JSON.stringify(result.usage||{}),reservation.lastInsertRowid);log('analysis','Jev diagnostic inference completed; no trade created');send(200,{ok:true,score:result.score,model,message:'Jev inference completed. Diagnostic fixture only; no trade created.'});}catch(e){const failure=safeFailure(e);run("UPDATE ai_calls SET status='failed',error_code=? WHERE id=?",failure,reservation.lastInsertRowid);log('analysis','Jev diagnostic inference failed: '+failure);send(502,{error:'Jev inference failed: '+failure});}finally{busy=false;}return;}
 if(path==='/api/connections/test'){if(!providerNames.includes(b.name)){send(400,{error:'Unknown provider'});return;}const saved=q('SELECT secret FROM connections WHERE name=?',b.name)[0];const secret=saved?decrypt(saved.secret,key):null;if(!secret){send(400,{error:'Save a key first'});return;}if(running||busy){send(409,{error:'Stop worker before testing connections'});return;}try{const result=await testConnection(b.name,secret||'');run('UPDATE connections SET tested=?,message=? WHERE name=? AND secret=?',result.ok?1:0,result.message,b.name,saved.secret);send(200,result);}catch{send(502,{error:'Connection probe failed'});}return;}
 if(path==='/api/settings'){if(running||busy){send(409,{error:'Stop worker before changing settings'});return;}if(typeof b.aiEnabled!=='boolean'||!Number.isInteger(b.aiDailyLimit)||b.aiDailyLimit<0||b.aiDailyLimit>1000){send(400,{error:'Invalid settings'});return;}const interval=b.aiIntervalMinutes??settings().ai_interval_minutes;if(!Number.isInteger(interval)||interval<5||interval>1440){send(400,{error:'AI request interval must be 5–1440 minutes'});return;}let threshold;try{threshold=scoreThreshold(b.aiMinScore??settings().ai_min_score);}catch{send(400,{error:'AI threshold must be between 0.5 and 1'});return;}const previous=settings(),provider=b.aiProvider??previous.ai_provider,model=b.aiModel??(provider===previous.ai_provider?previous.ai_model:defaultModels[provider as keyof typeof defaultModels]),rpcEnabled=b.rpcEnabled??!!previous.rpc_enabled,socialEnabled=b.socialEnabled??!!previous.social_enabled,rpcLimit=b.rpcDailyLimit??previous.rpc_daily_limit,socialLimit=b.socialDailyLimit??previous.social_daily_limit;if(!aiProviders.includes(provider)||typeof model!=='string'||!/^[a-zA-Z0-9_.:/-]{1,100}$/.test(model)||typeof rpcEnabled!=='boolean'||typeof socialEnabled!=='boolean'||!Number.isInteger(rpcLimit)||rpcLimit<0||rpcLimit>1000||!Number.isInteger(socialLimit)||socialLimit<0||socialLimit>1000){send(400,{error:'Invalid adapter settings'});return;}let limits;try{limits=riskInput(b,previous);}catch{send(400,{error:'Invalid paper risk limits'});return;}db.exec('BEGIN IMMEDIATE');try{run('UPDATE settings SET '+Object.keys(limits).map(k=>k+'=?').join(',')+' WHERE id=1',...Object.values(limits));run('UPDATE settings SET ai_enabled=?,ai_daily_limit=?,ai_provider=?,ai_model=?,rpc_enabled=?,social_enabled=?,rpc_daily_limit=?,social_daily_limit=? WHERE id=1',b.aiEnabled?1:0,b.aiDailyLimit,provider,model,rpcEnabled?1:0,socialEnabled?1:0,rpcLimit,socialLimit);run('UPDATE settings SET ai_min_score=?,ai_interval_minutes=? WHERE id=1',threshold,interval);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}log('control','Owner updated paper sizing and adapter limits');send(200,{ok:true});return;}
 if(path==='/api/start'){if(b.mode!=='paper'){send(400,{error:'Live execution is not implemented'});return;}if(busy){send(409,{error:'Previous cycle still completing'});return;}const s=settings();const required=[...(s.ai_enabled?[s.ai_provider]:[]),...(s.rpc_enabled?['solana']:[]),...(s.social_enabled?['x']:[])];for(const name of required)if(!q('SELECT name FROM connections WHERE name=? AND tested=1',name).length){send(400,{error:`Save and test ${name} before enabling its adapter`});return;}if(!running){running=true;generation++;log('control','Paper worker started');void tick();}send(200,{ok:true});return;}
 if(path==='/api/stop'){running=false;generation++;log('control','Stopped entries; positions retained. Paper exits also pause.');send(200,{ok:true});return;}
 send(404,{error:'Not found'});
 }catch{send(400,{error:'Request could not be processed'});}});
server.listen(Number(process.env.PORT||9010),process.env.HOST||'127.0.0.1',()=>console.log('Agent Trader listening; worker STOPPED; paper-only'));
for(const signal of ['SIGTERM','SIGINT'])process.on(signal,()=>{running=false;generation++;server.close(()=>{db.close();process.exit(0);});setTimeout(()=>process.exit(0),20000).unref();});
