import {rpc} from './providers.ts';
export const USDC='EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v';
export const TOKEN_PROGRAMS=['TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA','TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb'];
const alphabet='123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';
export function validWallet(value:any){if(typeof value!=='string'||value.length<32||value.length>44)return false;let n=0n;for(const c of value){const i=alphabet.indexOf(c);if(i<0)return false;n=n*58n+BigInt(i);}let bytes=0;while(n){bytes++;n>>=8n;}return bytes+(value.match(/^1*/)?.[0].length||0)===32;}
export function decimal(raw:string,places:number){if(!/^\d+$/.test(raw)||!Number.isInteger(places)||places<0||places>255)throw Error('Invalid token amount');const value=BigInt(raw).toString().padStart(places+1,'0');return places?(value.slice(0,-places)+'.'+value.slice(-places)).replace(/\.?0+$/,''):value;}
export function holdings(results:any[],owner:string){const m=new Map<string,any>();for(const result of results){if(!Array.isArray(result?.value))throw Error('Invalid token accounts');for(const entry of result.value){const info=entry?.account?.data?.parsed?.info,amount=info?.tokenAmount;if(!info||info.owner!==owner||!validWallet(info.mint)||!amount||!/^\d+$/.test(amount.amount)||!Number.isInteger(amount.decimals)||amount.decimals<0||amount.decimals>255)throw Error('Unparsed token account');const raw=BigInt(amount.amount);if(raw===0n)continue;const current=m.get(info.mint)||{mint:info.mint,raw:0n,decimals:amount.decimals,accounts:0,frozen:false};if(current.decimals!==amount.decimals)throw Error('Inconsistent token decimals');current.raw+=raw;current.accounts++;current.frozen ||= info.state==='frozen';m.set(info.mint,current);}}return [...m.values()].map(v=>({mint:v.mint,symbol:v.mint===USDC?'USDC':'Unverified token',amount:decimal(v.raw.toString(),v.decimals),decimals:v.decimals,accounts:v.accounts,frozen:v.frozen})).sort((a,b)=>a.mint===USDC?-1:b.mint===USDC?1:a.mint.localeCompare(b.mint));}
export class WalletReader{
 cache:any=null;flight:Promise<any>|null=null;lastAttempt=0;
 clear(){this.cache=null;}
 async read(address:string,key:string){if(this.cache?.address===address&&Date.now()-this.lastAttempt<90000)return this.cache;if(this.flight){await this.flight;return this.read(address,key);}if(Date.now()-this.lastAttempt<90000)return {address,status:'waiting',message:'Wallet refresh is limited to once every 90 seconds',sol:null,usdc:null,holdings:null,transactions:null};this.lastAttempt=Date.now();const old=this.cache?.address===address?this.cache:null;
 const task=(async()=>{const out:any={address,network:'Solana mainnet',status:'connected',fetchedAt:Date.now(),sol:null,usdc:null,holdings:null,transactions:null,errors:[],readOnly:true};const responses=await Promise.allSettled([rpc(key,'getBalance',[address,{commitment:'confirmed'}]),...TOKEN_PROGRAMS.map(programId=>rpc(key,'getTokenAccountsByOwner',[address,{programId},{encoding:'jsonParsed',commitment:'confirmed'}])),rpc(key,'getSignaturesForAddress',[address,{limit:20,commitment:'confirmed'}])]);
 const balance=responses[0];if(balance.status==='fulfilled'&&Number.isSafeInteger(balance.value?.value)&&balance.value.value>=0)out.sol=decimal(String(balance.value.value),9);else out.errors.push('SOL balance unavailable');
 const tokens=responses.slice(1,3);if(tokens.every(r=>r.status==='fulfilled'))try{out.holdings=holdings(tokens.map((r:any)=>r.value),address);out.usdc=out.holdings.find((h:any)=>h.mint===USDC)?.amount||'0';}catch{out.errors.push('Token holdings unavailable');}else out.errors.push('Token holdings unavailable');
 const history=responses[3];if(history.status==='fulfilled'&&Array.isArray(history.value)&&history.value.every((t:any)=>typeof t.signature==='string'&&/^[1-9A-HJ-NP-Za-km-z]{64,88}$/.test(t.signature))){out.transactions=history.value.slice(0,20).map((t:any)=>({signature:t.signature,at:typeof t.blockTime==='number'?t.blockTime*1000:null,status:t.err?'failed':t.confirmationStatus||'confirmed'}));}else out.errors.push('Recent transaction history unavailable');
 if(out.errors.length){out.status='partial';if(out.sol===null&&out.holdings===null&&out.transactions===null){if(old){this.cache={...old,status:'stale',errors:out.errors,message:'RPC unavailable; showing last successful snapshot'};return this.cache;}out.status='unavailable';}}out.message=out.errors.length?out.errors.join(' · '):'Confirmed on-chain snapshot · cached 90 seconds';this.cache=out;return out;})();this.flight=task;try{return await task;}finally{this.flight=null;}
 }
}
